import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Socials from "./components/Socials";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tee Jay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll`}
      >
        {children}
        <div className="flex justify-center items-center w-full">
        <Socials />
        </div>
      </body>
    </html>
  );
}
